### ISSUE TITLE
Zend Http Client is deprecated in Magento 2.4.6

### ISSUE THREAD

**Issue by netzkollektiv** [cobbyio/cobby-connector-magento2#8]
When placing an order in Magento v2.4.6 the extension / Magento is logging the following error. Please replace the deprecated Zend HTTP Client. Thank you! :-)

```[2023-05-15T11:22:58.444910+00:00] main.INFO: Exception: User Deprecated Functionality: Class is deprecated in 
web/vendor/magento/framework/HTTP/ZendClient.php on line 27 in 
web/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(16384, 'Class is deprec...', '/var/www/share/...', 27)
#1 web/vendor/magento/framework/HTTP/ZendClient.php(27): trigger_error('Class is deprec...', 16384)
#2 web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\HTTP\ZendClient->__construct(NULL, NULL)
#3 web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#4 web/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array)
#5 web/generated/code/Magento/Framework/HTTP/ZendClientFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('\\Magento\\Framew...', Array)
#6 web/vendor/cobbyio/cobby-connector-magento2/Helper/CobbyApi.php(78): Magento\Framework\HTTP\ZendClientFactory->create()
#7 web/vendor/cobbyio/cobby-connector-magento2/Helper/CobbyApi.php(115): Cobby\Connector\Helper\CobbyApi->restPost('magento/notify', Array)
#8 web/vendor/cobbyio/cobby-connector-magento2/Helper/Queue.php(128): Cobby\Connector\Helper\CobbyApi->notifyCobbyService('product', 'save', '16174')
#9 web/vendor/cobbyio/cobby-connector-magento2/Observer/OrderPlaced.php(50): Cobby\Connector\Helper\Queue->enqueueAndNotify('product', 'save', Array)
#10 web/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Cobby\Connector\Observer\OrderPlaced->execute(Object(Magento\Framework\Event\Observer))
#11 web/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Cobby\Connector\Observer\OrderPlaced), Object(Magento\Framework\Event\Observer))
#12 web/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#13 web/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('sales_order_pla...', Array)
#14 web/vendor/magento/module-sales/Model/Order.php(1229): Magento\Framework\Event\Manager\Proxy->dispatch('sales_order_pla...', Array)
#15 web/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
#16 web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
#17 web/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
#18 web/generated/code/Magento/Sales/Model/Order/Interceptor.php(32): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)
#19 web/vendor/magento/module-sales/Model/Service/OrderService.php(207): Magento\Sales\Model\Order\Interceptor->place()
#20 web/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
#21 web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
#22 web/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#23 web/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(32): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, Array)
#24 web/vendor/magento/module-quote/Model/QuoteManagement.php(624): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
#25 web/vendor/magento/module-quote/Model/QuoteManagement.php(500): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#26 web/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#27 web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', Array)
#28 web/vendor/magento/module-sales-rule/Plugin/CouponUsagesIncrement.php(54): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#29 web/vendor/magento/framework/Interception/Interceptor.php(135): Magento\SalesRule\Plugin\CouponUsagesIncrement->aroundSubmit(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), Object(Magento\Quote\Model\Quote\Interceptor))
#30 web/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
#31 web/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(32): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', Array, NULL)
#32 web/vendor/magento/module-quote/Model/QuoteManagement.php(458): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#33 web/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->placeOrder(2082511, NULL)
#34 web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('placeOrder', Array)
#35 web/vendor/paypal/module-braintree-core/Plugin/OrderCancellation.php(64): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(2082511, NULL)
#36 web/vendor/magento/framework/Interception/Interceptor.php(135): PayPal\Braintree\Plugin\OrderCancellation->aroundPlaceOrder(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), 2082511, NULL)
#37 web/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}('2082511', NULL)
#38 web/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(23): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('placeOrder', Array, NULL)
#39 web/vendor/magento/module-quote/Model/GuestCart/GuestCartManagement.php(87): Magento\Quote\Model\QuoteManagement\Interceptor->placeOrder('2082511', NULL)
#40 web/vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php(141): Magento\Quote\Model\GuestCart\GuestCartManagement->placeOrder('t92qLgCS2V1KG6s...')
#41 web/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('t92qLgCS2V1KG6s...', 'dominik.krebs@n...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#42 web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#43 web/vendor/teambank/ratenkaufbyeasycredit-plugin-magento-2/Plugin/InterceptGuestSaveOrder.php(28): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('t92qLgCS2V1KG6s...', 'dominik.krebs@n...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#44 web/vendor/magento/framework/Interception/Interceptor.php(135): Netzkollektiv\EasyCredit\Plugin\InterceptGuestSaveOrder->aroundSavePaymentInformationAndPlaceOrder(Object(Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor), Object(Closure), 't92qLgCS2V1KG6s...', 'dominik.krebs@n...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#45 web/vendor/payone-gmbh/magento-2/Model/Plugins/GuestPaymentInformationManagement.php(100): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('t92qLgCS2V1KG6s...', 'dominik.krebs@n...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#46 web/vendor/magento/framework/Interception/Interceptor.php(135): Payone\Core\Model\Plugins\GuestPaymentInformationManagement->aroundSavePaymentInformationAndPlaceOrder(Object(Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor), Object(Closure), 't92qLgCS2V1KG6s...', 'dominik.krebs@n...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#47 web/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('t92qLgCS2V1KG6s...', 'dominik.krebs@n...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#48 web/generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, NULL)
#49 [internal function]: Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder('t92qLgCS2V1KG6s...', 'dominik.krebs@n...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#50 web/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#51 web/vendor/magento/module-webapi/Controller/Rest.php(202): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#52 web/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#53 web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#54 web/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#55 web/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#56 web/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#57 web/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#58 web/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#59 {main} {"exception":"[object] (Exception(code: 0): User Deprecated Functionality: Class is deprecated in web/vendor/magento/framework/HTTP/ZendClient.php on line 27 at 
web/vendor/magento/framework/App/ErrorHandler.php:62)"} []```

**Comment by dimajanzen** [comment]
Thanks for the notification, the problem has been fixed in version 2.4.7 and the new relese is available.

**Comment by netzkollektiv** [comment]
Unfortunately LaminasClientFactory does not exist in Magento 2.4.5, which now leads to the following error in ealier versions than 2.4.6:
```
 ./bin/magento s:di:com
Compilation was started.
Area configuration aggregation... 5/9 [===============>------------]  55% 20 secs 364.0 MiB
In ClassReader.php line 57:

  Impossible to process constructor argument Parameter #2 [ <required> Magento\Framework\HTTP\LaminasClientFactory $httpClientFactory ] of Cobby\Connector\Helper\CobbyApi class


In GetParameterClassTrait.php line 34:

  Class "Magento\Framework\HTTP\LaminasClientFactory" does not exist
```

**Comment by dimajanzen** [comment]
Thanks for the feedback, we are still looking into how to resolve this in a long-term manner.

**Comment by dimajanzen** [comment]
Hi,

we have replaced the Zend library with curl, so everything is working again. Thanks for the report.
